installation: bump dependencies
📁 invenio-app-rdm (14.0.0b0.dev3 -> 14.0.0b1.dev1 🚀)

    📦 release: v14.0.0b1.dev1
    📦 release: v14.0.0b1.dev0
    installation: bump collections, communities, and rdm-records
    feat(deletion-request): different checklist for immediate and request
    feat(record-deletion): add notifications; last replied sort
    fix(record-deletion): fix request resolution with deleted record with draft
    req: add deletion reason and justification to req details
    UX: display error message if req fails
    fix: bail early if recordDeletion not found
    fix: case when last_reply none; deletion modal state reset on close
    feat(deletion-request): link to existing deletion request if exists
    UI: record_deletion: fix deletion request; remove overrides; fix redirection
    UI: update record deletion modal and add checkboxes
    UI: adjust frontend to new RecordDeletion policy
    UI: show message on checklist fail
    vocab: load removal_reasons from vocabulary
    refactor: extract checklist to config
    UI: add delete to manage dropdown and deposit page
    refactor: move record deletion to components
    UI: add overridables to modal
    UI: record deletion modal
    fix(record-deletion): config: add config; load config from app rdm
    admin: refactor moderation request structure; fix typos
    admin: create requests details view
    admin: create moderation->requests panel
    UI: requests: add template for record deletion request type
    requests: fix deleted request resolution on requests
    fix: correctly retrieve error message
    release: v14.0.0b0.dev4
    deposit: pass to the form config the published record if we edit one
    * The published record is used to compare published DOI but it can be
      used also to compare with the published state of an editing draft.
    help: correct search instructions for missing fields (review suggestions)

    help: correct search instructions for missing fields

📁 invenio-checks (1.0.0 -> 2.0.0 ⚠️)

    📦 release: v2.0.0
    installation: bump invenio-communities

📁 invenio-collections (1.0.0 -> 2.0.0 ⚠️)

    📦 release: v2.0.0
    installation: bump communities and rdm-records
    alembic: depend on communities instead of rdm-records

    The alembic dependency currently points to invenio-rdm-records,
    but no models from RDM records are referenced at the database
    layer — only community models are used.

    This PR changes the dependency to use the latest alembic from
    invenio-communities.

📁 invenio-communities (20.0.0 -> 21.0.0 ⚠️)

    📦 release: v21.0.0
    installation: bump invenio-requests
    release: v20.2.0
    release: v20.1.0
    setup: bump invenio-requests
    fix: correct community topic typo
    fix(views): handle permission denied error in the UI view functions

    * previously, we only handled the `PermissionDeniedError` which is a
      subclass of `PermissionDenied`, and a sibling of
      `RecordPermissionDeniedError` (which was unhandled)
    * since we want to handle both permission denied errors the same, we
      just register a handler for the parent exception class here

📁 invenio-db (2.1.0 -> 2.1.1 🐛)

    release: v2.1.1
    fix(setup): pin sqlalchemy-utils

    * multiple errors on multiple packages like:
      sqlalchemy.exc.OperationalError: (psycopg2.errors.ObjectInUse) database
      "invenio" is being accessed by other users DETAIL: There are 2 other
      sessions using the database.

    release: v2.1.0
    workflows: switch to centralized workflows

📁 invenio-jobs (4.3.2 -> 5.0.0 ⚠️)

    release: v5.0.0
    setup: bump invenio-users-resources

📁 invenio-logging (4.1.0 -> 4.1.1 🐛)

    release: v4.1.1
    ext: add request_id filter to root logger
    console: fix handler level

📁 invenio-oauthclient (5.2.0 -> 5.3.0 🌈)

    📦 release: v5.3.0
    feat(contrib): add EOSC EU Node AAI OIDC provider

📁 invenio-rdm-records (20.0.1 -> 21.0.0 ⚠️)

    📦 release: v21.0.0
    fix(record-deletion): align marshmallow schema with request actions
    installation: bump invenio-communities and invenio-checks
    feat(deletion-request): different checklist for immediate and request
    feat(record-deletion): add notifications; minor fixes
    fix(record-deletion): check for authenticated users only
    fix(record-deletion): update policy descriptions
    fix(record-deletion): add check for system accept; fix tests
    fix(record-deletion): language; tombstone should have accepter's ID
    fix(record-deletion): enhance request policy description
    fix: request deletion link for published record draft
    feat(deletion-request): add tags for valid removal reasons
    fix: record deletion request self_html to include /me
    test(record-deletion-request): cover service call and deletion policies
    refactor(record_deletion): adapt to deletion policy
    refactor(deletion_policy): move to separate file and add to service config
    feat(schema): allow `removed_by` to be passed to tombstone schema

    * Allows loading the field in the schema.
    * If not passed, defaults to the `identity.id` of the deletion action.
    feat(schema): add `deletion_policy` to record tombstone
    feat: add support to request deletion of a record
    config: add user record deletion config

    store policies in config as list of classes rather than code
    service: create RDMRecordDeletionPolicy
    setup: remove unused ftfy pin to remove pkg-resources usage
    chore(js-tests): upgrade react-overridable major version
    fix(CreatibutorsModal): get identifier scheme from recent suggestions
    fix(datacite test link): update Datacite test DOI link
    bug: invalid datacite test mode link

    release: v20.2.0
    * The versions of react-invenio-forms and react-overridable have been
    bumped to incorporate the new common props objects and the new devtools.

    BREAKING CHANGE: a number of existing Overridable IDs have been renamed
    to improve compliance with naming conventions and further improve the
    developer experience. The full list of renamed IDs is in CHANGES.rst. We
    originally discussed removing some too-granular Overridables in the
    InvenioRDM telecon of 2025-09-09, but in the end we decided *not* to
    remove any.

    release: v20.1.0
    setup: bump invenio-jobs and invenio-vocabularies
    fix: improve rendering of ErrorMessage

    release: v20.0.3
    fix(deposit-form): correct wrong propType for optionalDOItransitions
    fix(deposit-form): on delete draft discard all changed pids
    * discard all draft pids if there is no published record (i.e. new version or new draft)
    * discard all draft pids that are not in the published record

    release: v20.0.2
    fix(optional-doi): show correctly showed value on form initialization
    * uses published record doi to check if the managed DOI can be unreserved.
    * `shouldCheckForExplicitDOIReservation` condition is evaluated against
      pids.doi because before it was taking into account only the pids object
      and there more pids could be present e.g. oai
    fix(iiif): add error handler for `MultimediaImageNotFound`

📁 invenio-requests (8.1.0 -> 10.0.1 ⚠️)

    📦 release: v10.0.1
    fix(events): avoid indexing request on delete event

    * When we log delete events it is not necessary to also index the
      associated request, since it will anyways be deleted from the index.
    mappings: fix dynamic template for `created_by`
    📦 release: v10.0.0
    global: add `Request.last_reply` systemfield

    * Adds a computed and search-indexed field for getting the last reply
      (i.e. the last comment event) for a request.
    release: v9.0.1
    release: v9.0.0
    setup: bump invenio-users-resources
    UI: improve record-deletion accept label

📁 invenio-search-ui (4.1.1 -> 4.1.2 🐛)

    release: v4.1.2

📁 invenio-users-resources (8.3.0 -> 9.0.1 ⚠️)

    📦 release: v9.0.1
    fix(entity_resolvers): handle `None` user entity
    release: vv9.0.0
    service: add task to import domain blocklist

    - Added a Celery task to import a domain blocklist from a URL (e.g.
      StopForumSpam or DisposableEmailDomains).
    users: restrict access to item endpoint

    - change the default authorization access of users endpoint
      from AnyUser to AuthenticatedUser when profile
      is restricted
    - apply the same restriction to user's avatar endpoint
    - return 404 instead of 403 when permission is denied

📁 invenio-vocabularies (8.1.0 -> 9.0.0 ⚠️)

    release: v9.0.0
    setup: bump invenio-jobs
    release: v8.3.0
    subjects: config: Search scheme field for composite and filter query
    release: v8.2.1
    fix: string replacement of timestamps
    * Adjusted the tests to use Python 3.9 compatible timestamps with +00:00
    instead of Z
    fix: python <3.10 incompatibility with ISO 8601
    * In Python <3.10, `fromisoformat` cannot parse the `Z` suffix in ISO
    8601 strings which could cause incompatibilities with the technically
    valid ISO timestamps used in jobs

    * Added a replacement of `Z` with the supported equivalent `+00:00`
    everywhere an ISO timestamp is parsed
    fix: remove `arrow` from tests

    * Removed `arrow` package from tests, so `invenio-vocabularies` no
    longer has any usage of `arrow`

    * Updated ROR tests to use full ISO timestamps which are compatible with
    the refactored job implementation
    fix: remove arrow usage from everywhere except tests
    fix: remove arrow usage from names datastream

    * The names datastream uses very simple date parsing. We do not need
    arrow for such a simple task, so it has been removed for improved
    simplicity
    fix(jobs): remove string casts from `since`

    * Jobs currently use a string-cast `since` parameter rather than keeping
    it as the Python `datetime` obj due to a previous issue that wasn't
    fully investigated

    * Provisionally removed the string casts which need to be tested
    names: orcid job: fix since argument not working
    release: v8.2.0
    tasks: fix error name
    datastreams: Add skip warning for errored transformed entries
    names: datastreams: write and display errors instead of raise

🚨 Major version bumps (potentially breaking changes):
📁 cffi (1.17.1 -> 2.0.0 ⚠️)
📁 cryptography (45.0.7 -> 46.0.1 ⚠️)
📁 ftfy (4.4.3 -> 6.3.1 ⚠️)
📁 pycountry (22.3.5 -> 24.6.1 ⚠️)
📁 pytest-cov (6.2.1 -> 7.0.0 ⚠️)