installation: bump dependencies
📁 invenio-access (3.0.2 -> 4.0.0 ⚠️)

    release: v4.0.0
    setup: bump major dependencies

📁 invenio-accounts (5.1.7 -> 6.0.0 ⚠️)

    release: v6.0.0
    fix: cookie_app and users not using same app

    * the problem is since cookie_app and users use different app one closes
      the connection to the database first which is bad
    fix: add translation flag for publishing
    setup: bump major dependencies

📁 invenio-administration (2.9.0 -> 3.0.0 ⚠️)

    release: v3.0.0
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-app (1.5.1 -> 2.0.0 ⚠️)

    release: v2.0.0
    factory: change to new TRUSTS_HOSTS from flask

    * flask>=3.1.0 introduced a new configuration variable TRUSTS_HOSTS.
      this removes the necessity to use APP_ALLOWED_HOSTS and the code around
      it.
    setup: bump major dependencies

📁 invenio-app-rdm (13.0.0b1.dev24 -> 13.0.0b2.dev0 ⚠️)

    release: v13.0.0b2.dev0
    setup: remove flask pin
    setup: change to reusable workflows
    setup: bump major dependencies
    release: v13.0.0b1.dev25
    doi: handle UI for optional DOI feature
    theme: put banner message below other objects
    pages: do not create a static page if it already exists

📁 invenio-assets (3.1.0 -> 4.0.0 ⚠️)

    release: v4.0.0
    setup: bump invenio dependencies

📁 invenio-banners (3.2.0 -> 4.0.0 ⚠️)

    release: v4.0.0
    fix: make github actions work again

    * the dependencies on github actions couldn't be resolved without that
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-base (1.4.0 -> 2.0.0 ⚠️)

    release: v2.0.0
    setup: set flask,werkzeug min version

    * flask-alembic >= v3.0.0 (dependency of invenio-db) needs flask>=3.0.
      flask-alembic >= v3.0.0 is required because otherwise the removable
      of 'db' property in flask-sqlalchemy is a problem

    * the test if could be removed because of the min version now supported
    jws: move functionality from itsdangerous

    * itsdangerous v2.1.0 removes the jws functionality. to have an easy
      follow up without rewrite the functionality has been copy pasted
    setup: remove upper pins

📁 invenio-cache (1.3.1 -> 2.0.0 ⚠️)

    release: v2.0.0
    setup: replace invenio-accounts with flask-login

    * this breaks circular dependencies
    setup: bump major dependencies

📁 invenio-celery (1.3.2 -> 2.0.0 ⚠️)

    release: v2.0.0
    setup: change to reusable workflows
    setup: bump invenio dependencies
    fix: celery deprecation warning

    * CPendingDeprecationWarning: The broker_connection_retry configuration
      setting will no longer determine whether broker connection retries are
      made during startup in Celery 6.0 and above. If you wish to retain the
      existing behavior for retrying connections on startup, you should set
      broker_connection_retry_on_startup to True.

    * https://github.com/celery/celery/discussions/8314
    setup: increase celery dep

📁 invenio-communities (17.7.1 -> 18.0.0.dev1 ⚠️)

    📦 release: v17.7.1
    schema: skip unknown fields when loading organizations
    📦 release: v17.7.0
    release: v18.0.0.dev1
    fix: docs reference target not found
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-db (1.3.1 -> 2.0.0 ⚠️)

    release: v2.0.0
    uow: possible solution for the rollback problem

    * the rollback should only rollback whats in that savepoint. using
      session.begin_nested creates a subtransaction which can then
      rolledback
    fix: select of BinaryExpressions

    * sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other
      columns clause element expected, got
      [<sqlalchemy.sql.elements.BinaryExpression object at 0x7fa3a0>,
      <sqlalchemy.sql.elements.BinaryExpression object at 0x7fa3ad246690>].
      Did you mean to say select(<sqlalchemy.sql.elements.BinaryExpression
      object at 0x7fa3b1145c10>, <sqly.sql.elements.BinaryExpression object at
      0x7fa3ad246690>)

      don't give the array to the select but give the elements to the select
      method

    * AttributeError: 'Engine' object has no attribute 'execute' -> change
      to session

    * TypeError: scoped_session.execute() got an unexpected keyword argument
      'a' -> change to dict
    setup: increase flask-alembic

    * flask-alembic >= 3.0 needs flask >= 3.0 and flask-sqlalchemy >= 3.0

    * added some explanation comments

    * apply db.session.query over Model.query syntax
    setup: increase min sqlalchemy dependency

    * apply new correct return values to cli calls

    * refactor code

    * remove unused code
    cli: password is per default hided

    * this leads to the problem that the program couldn't connect to the
      database
    refactor: move MockEntryPoint to independent file

    * this change makes it possible to import the MockEntryPoints from an
      independend file. this class is used in two tests but defined in one
      of them. placing it into a separated file makes it independent.
    setup: remove upper pins
    fix: VARCHAR needs length on mysql
    fix: remove warning and black problems

    * added D202, pydocstyle and black do not habe the same opinion

    * remove warning by using StringEncryptedType instead of EncryptedType.
      This removes a warning and there is further a notice in the code that
      the base type of EncryptedType will change in the future and it is
      better to replace it with StringEncryptedType
    fix: WeakKeyDictionary

    * the error indicates that db.init_app is not called, but it is and it
      works in other contexts. It may that the `db = invenio_db = shared.db`
      line in conftest.py is not working as expected anymore. The only found
      solution is this. The drawback is, if that is the only solution it has
      to be done also in the other packages which are using this function.
      With the default value it is backward compatible but as the tests
      indicates it may not work without adding the db parameter to the
      function call
    change: add proxy file

    * use the proxy file instead of creating the _db variable in both files

    * this removes a DeprecationWarning from flask-sqlalchemy, which
      states that the support of the use '.db' will be removed
    change: remove click 3 compatibility
    fix: tests LocalProxy

    * it is not working anymore with localproxy and it seams not necessary
    setup: increase flask-sqlalchemy version

📁 invenio-drafts-resources (5.1.0 -> 6.0.0 ⚠️)

    release: v6.0.0
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-files-rest (2.2.4 -> 3.0.0 ⚠️)

    release: v3.0.0
    filename: replace encoding/decoding
    fix: alembic assert error

    * AssertionError: assert not [[('modify_type', None, 'files_objecttags',
      'key', {'existing_comment': None, 'existing_nullable': False,
      'existing_server_default': False}, TEXT(), ...)]]

    * newer sqlalchemy + alembic is complaining about the mismatch between
      model and alembic recipe
    fix: max content type
    fix: werkzeug changed raise handling for tests

    * werkzeug is not more raising exceptions but giving it to the response
      which is more like http requests work
    fix: docs reference target not found
    fix: filename is marked as byte
    setup: bump invenio dependencies

📁 invenio-formatter (2.0.4 -> 3.0.0 ⚠️)

    release: v3.0.0
    setup: bump major dependencies

📁 invenio-github (1.5.4 -> 2.0.0 ⚠️)

    release: v2.0.0
    comp: make compatible to flask-sqlalchemy>=3.1
    setup: bump major dependencies

📁 invenio-i18n (2.2.0 -> 3.0.0 ⚠️)

    release: v3.0.0
    setup: update dependencies

📁 invenio-indexer (2.4.0 -> 3.0.0 ⚠️)

    release: v3.0.0
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-jobs (1.1.1 -> 3.0.0.dev1 ⚠️)

    release: v3.0.0.dev1
    fix: tests by skipping alembic
    fix: alembic problem

    * ('modify_type', None, 'jobs_run', 'status', {'existing_comment': None,
      'existing_nullable': False, 'existing_server_default': False},
      CHAR(length=1), ...)]])
    comp: make compatible to flask-sqlalchemy>=3.1
    setup: change to reusable workflows
    setup: bump major dependencies
    tasks: use utcnow
    📦 release: v1.1.1
    tasks: use utcnow
    release: v2.0.0
    job: refactor args

    * adds PredefinedArgsSchema schema class with predefined args, including
      `since`.
    * changes JobType public/private interface to make it easier to define
      your own job types
    * logs celery tasks error message and shows it in the UI
    * removes unused code

📁 invenio-jsonschemas (1.1.5 -> 2.0.0 ⚠️)

    release: v2.0.0
    fix: JsonRef not serializable

    * TypeError: Object of type JsonRef is not JSON serializable
    setup: bump major dependencies

📁 invenio-logging (2.1.4 -> 4.0.2 ⚠️)

    📦 release: v4.0.2
    sentry: move imports inside extension class initializer
    📦 release: v2.1.4
    sentry: move imports inside extension class initializer
    📦 release: v4.0.1
    sentry: import-detect sentry_sdk usage
    📦 release: v2.1.3
    sentry: import-detect sentry_sdk usage
    release: v3.0.0
    setup: bump invenio dependencies
    release: v3.0.0
    setup: change sentry_sdk to sentry

    * sentry_sdk could make problem, sentry-sdk too. last release had to be
      yanked because of that problem. changing to sentry only should fix it

📁 invenio-mail (2.1.1 -> 2.2.0 🌈)

    release: v2.2.0
    Add exception handling and retry mechanism (inveniosoftware/invenio-mail#67)

    * Add exception handling and retry mechanism.
    * Retry with exponential backoff with random jitter to prevent "Thundering herd problem".

📁 invenio-notifications (0.6.1 -> 1.0.0 ⚠️)

    release: v1.0.0
    setup: bump major dependencies

📁 invenio-oaiserver (2.3.0 -> 3.1.0 ⚠️)

    📦 release: v3.1.0
    percolator: use `OAISERVER_RECORD_INDEX` to determine percolator index

    * Instead of relying on the default `RecordIndexer` class to determine
      the percolator index, we reuse the `OAISERVER_RECORD_INDEX` config variable.
    📦 release: v2.3.0
    percolator: use `OAISERVER_RECORD_INDEX` to determine percolator index

    * Instead of relying on the default `RecordIndexer` class to determine
      the percolator index, we reuse the `OAISERVER_RECORD_INDEX` config variable.
    setup: change to reusable workflows
    release: v3.0.0
    fix: tests, apply invenio-indexer change
    fix: docs reference target not found
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-oauth2server (2.3.1 -> 3.0.0 ⚠️)

    release: v3.0.0
    setup: move to flask-oauthlib-invenio
    global: replace werkzeug.url with urllib.parse

    * replacing werkzeug.url with urllib.parse makes also _compat and
      monkeypatching obsolete and therefore has been removed
    fix: LegacyAPIWarning

    * The Query.get() method is considered legacy as of the 1.x series of
      SQLAlchemy and becomes a legacy construct in 2.0. The method is now
      available as Session.get() (deprecated since: 2.0) (Background on
      SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    fix: DeprecationWarning:

    * The 'EncryptedType' class will change implementation from
      'LargeBinary' to 'String' in a future version. Use 'StringEncryptedType'
      to use the 'String' implementation.
    setup: bump major dependencies
    release: v2.4.1
    setup: change to reusable workflows
    setup: pin dependencies
    release: v2.4.0
    global: remove six usage

    * replace six with builtin
    compatibility: to werkzeug >= 2.3.0
    setup: unpin wtforms dependency

    * wtforms: apply changed api
    fix: DeprecationWarning HTMLString

    * 'HTMLString' will be removed in WTForms 3.0. Use 'markupsafe.Markup'
      instead.

    * this is a step to remove the upper pin to <= 3.0.0
    Settings: update page to reflect additional required parameter

📁 invenio-oauthclient (4.1.3 -> 5.1.0 ⚠️)

    release: v5.1.0
    fix: DeprecationWarning:

    * The 'EncryptedType' class will change implementation from
      'LargeBinary' to 'String' in a future version. Use 'StringEncryptedType'
      to use the 'String' implementation.
    fix: TypeError

    * op.execute() takes 2 positional arguments but 3 were given
    setup: move to flask-oauthlib-invenio
    release: v5.0.0
    fix: sqlalchemy.exc.ArgumentError:

    * Strings are not accepted for attribute names in loader options; please
      use class-bound attributes directly.

    * sqlalchemy >= 2.0
    global: use invenio_base.jws not itsdangerous
    setup: bump major dependencies

📁 invenio-pages (4.1.2 -> 5.0.0 ⚠️)

    release: v5.0.0
    comp: make compatible to flask-sqlalchemy>=3.1
    setup: bump major dependencies

📁 invenio-pidstore (1.3.4 -> 2.0.0 ⚠️)

    release: v2.0.0
    fix: docs reference target not found
    setup: bump invenio dependencies

📁 invenio-previewer (2.2.2 -> 3.0.0 ⚠️)

    release: v3.0.0
    fix: tests, compatibility with sqlalchemy>=2

    * session handling problem
    setup: bump major dependencies
    release: v2.3.0
    zip: move fullscreen.js to fix the zip previewer

    * the zip previewer still referenced fullscreen.js via its old location
    * move the open_pdf.js as well, to not have a directory for a single
      file
    pdfjs: upgrade to pdf.js v4

    * the new assets are basically vanilla js targeting the browser already
    * this doesn't require a build step and allows the assets to be placed
      in the static directory, avoiding a build step and allowing for
      deduplication across themes
    * the jinja template is also deduplicated similarly, by being placed
      outside of any theme directory
    * implemented functionality with pdfjs-dist v4:
    > page navigation: previous/next/jump
    > zoom
    > fullscreen

📁 invenio-rdm-records (16.4.2 -> 17.0.0.dev1 ⚠️)

    📦 release: v16.4.2
    rights: fix serialize condition for controlled license
    release: v17.0.0.dev1
    fix: flask-sqlalchemy.pagination >= 3.0.0

    * this is a compatibility fix. the old compatibility commit was wrong.
      they are not interchangable
    comp: make compatible to flask-sqlalchemy>=3.1
    setup: change to reusable workflows
    setup: bump major dependencies
    doi: handle UI for optional DOI feature

📁 invenio-records (2.4.1 -> 3.0.2 ⚠️)

    release: v3.0.2
    fix: the correct handling is done in the iterator

    * the thinking of handling negative revision numbers in this line with
      the list was wrong
    release: v3.0.1
    fix: alembic recipe column not altered

    * produces error on the ext.alembic.compare_metadata() test on other
      packages
    release: v3.0.0
    fix: docs reference target not found
    fix: IndexError: negative indexes not allowed

    * IndexError: negative indexes are not accepted by SQL index / slice
      operators

    * sqlalchemy >= 2.0.0 removed the possibility to have negative indices
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-records-permissions (0.22.0 -> 1.0.0 ⚠️)

    release: v1.0.0
    setup: bump major dependencies

📁 invenio-records-resources (6.5.0 -> 7.0.0 ⚠️)

    release: v7.0.0
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-records-rest (2.4.1 -> 3.0.0 ⚠️)

    release: v3.0.0
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-records-ui (1.2.2 -> 2.0.0 ⚠️)

    release: v2.0.0
    setup: bump major dependencies

📁 invenio-requests (5.5.0 -> 6.0.0.dev1 ⚠️)

    release: v6.0.0.dev1
    fix: sqlalchemy.exc.ArgumentError

    * Textual SQL expression 'SELECT setval(pg_get_seri...' should be
      explicitly declared as text('SELECT setval(pg_get_seri...')
    comp: make compatible to flask-sqlalchemy>=3.1
    setup: bump major dependencies

📁 invenio-rest (1.5.0 -> 2.0.0 ⚠️)

    release: v2.0.0
    fix: set_cookie needs a str
    fix: cookie_jar not in FlaskClient

    * there was a refactoring done in werkzeug see
      https://github.com/pallets/werkzeug/pull/2637
    fix: set_cookie needs a str

    * but the tests are using the _get_new_csrf_token directly too and then
      a byte value is returned which is wrong
    global: remove try except for jws

    * increase itsdangerous and use invenio-base for jws now exclusively
      since invenio-base has been upgraded to >=2.0.0
    setup: bump major dependencies

📁 invenio-search (2.4.1 -> 3.0.0 ⚠️)

    release: v3.0.0
    fix: tests

    * that is a proactive fix. it happens locally but not really on github.
      this should be reconsidered.
    setup: change to reusable workflows
    setup: bump major dependencies

📁 invenio-search-ui (3.0.1 -> 4.0.0 ⚠️)

    release: v4.0.0
    refactor: blueprint creation to new style
    setup: bump major dependencies

📁 invenio-stats (4.2.1 -> 5.0.0 ⚠️)

    release: v5.0.0
    setup: bump major dependencies

📁 invenio-theme (3.5.1 -> 4.0.1 ⚠️)

    📦 release: v4.0.1
    form: some UI fixed for the deposit form
    release: v4.0.0
    setup: bump major dependencies

📁 invenio-userprofiles (3.0.1 -> 4.0.0 ⚠️)

    release: v4.0.0
    setup: bump major dependencies

📁 invenio-users-resources (6.1.3 -> 7.0.0.dev1 ⚠️)

    release: v7.0.0.dev1
    setup: change to reusable workflows
    setup: bump major dependencies
    📦 release: v6.1.3
    services: explicitly set max results to 10,000 for admin user search
    📦 release: v6.1.2
    📦 release: v6.1.3
    services: explicitly set max results to 10,000 for admin user search
    📦 release: v6.1.2

📁 invenio-vocabularies (6.9.0 -> 7.0.0.dev1 ⚠️)

    release: v7.0.0.dev1
    comp: make compatible to flask-sqlalchemy>=3.1
    setup: change to reusable workflows
    setup: bump major dependencies
    release: v6.10.1
    names: drop unique constraint on internal id
    release: v6.10.0
    names: add internal id to identify the names